services:
  #
  learnup_minio_storage_service:
    container_name: learnup_minio
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: root_user
      MINIO_ROOT_PASSWORD: root_password
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - learnup_network
  #
  learnup_redis_service:
    container_name: learnup_redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - learnup_network
  #
  learnup_main_database_service:
    container_name: learnup_main_database
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: learnup_db
    networks:
      - learnup_network
  #
  learnup_app_service:
    container_name: learnup_app
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - learnup_main_database_service
      - learnup_minio_storage_service
      - learnup_redis_service
    networks:
      - learnup_network

networks:
  learnup_network:
    driver: bridge