services:
  #
  learnup_minio_storage_service:
    container_name: learnup_minio
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - learnup_network
  #
  learnup_redis_service:
    container_name: learnup_redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - learnup_network
  #
  learnup_main_database_service:
    container_name: learnup_main_database
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${MAIN_DB_USERNAME}
      POSTGRES_PASSWORD: ${MAIN_DB_PASSWORD}
      POSTGRES_DB: ${MAIN_DB_NAME}
    networks:
      - learnup_network
  #
  learnup_app_service:
    container_name: learnup_app
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - learnup_main_database_service
      - learnup_minio_storage_service
      - learnup_redis_service
    environment:
      # minio
      LEARNUP_MINIO__URL: ${MINIO_URL}
      LEARNUP_MINIO__USERNAME: ${MINIO_USERNAME}
      LEARNUP_MINIO__PASSWORD: ${MINIO_PASSWORD}
      LEARNUP_MINIO__REGION: ${MINIO_REGION}
      # redis
      LEARNUP_REDIS__HOST: ${REDIS_HOST}
      LEARNUP_REDIS__PORT: ${REDIS_PORT}
      # main db
      LEARNUP_MAIN_DB__HOST: ${MAIN_DB_HOST}
      LEARNUP_MAIN_DB__USERNAME: ${MAIN_DB_USERNAME}
      LEARNUP_MAIN_DB__PASSWORD: ${MAIN_DB_PASSWORD}
      LEARNUP_MAIN_DB__NAME: ${MAIN_DB_NAME}
      LEARNUP_MAIN_DB__PORT: ${MAIN_DB_PORT}
      # smtp
      LEARNUP_SMTP__HOST: ${SMTP_HOST}
      LEARNUP_SMTP__PORT: ${SMTP_PORT}
      LEARNUP_SMTP__USERNAME: ${SMTP_USERNAME}
      LEARNUP_SMTP__PASSWORD: ${SMTP_PASSWORD}
      # app
      LEARNUP_APP__PORT: ${APP_PORT}
    networks:
      - learnup_network
    volumes:
      - ./log:/app/log

networks:
  learnup_network:
    driver: bridge
