// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login a user and return an access token",
                "parameters": [
                    {
                        "description": " ",
                        "name": "loginRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_ladmakhi81_learnup_internals_auth_dto_req.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/types.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_ladmakhi81_learnup_internals_auth_dto_res.LoginRes"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    }
                }
            }
        },
        "/categories/admin/": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Create a new category",
                "parameters": [
                    {
                        "description": " ",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_ladmakhi81_learnup_internals_category_dto_req.CreateCategoryReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/types.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_ladmakhi81_learnup_internals_category_dto_res.CreateCategoryRes"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    }
                }
            }
        },
        "/categories/admin/page": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Get a paginated list of categories",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Number of items per page",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": " ",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/types.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/types.PaginationRes"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    }
                }
            }
        },
        "/categories/admin/tree": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Get categories as a tree structure",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/types.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_ladmakhi81_learnup_internals_category_dto_res.GetCategoriesTreeRes"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ApiResponse"
                        }
                    }
                }
            }
        },
        "/categories/admin/{categoryId}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Delete a category by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": " ",
                        "name": "categoryId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    }
                }
            }
        },
        "/courses/admin": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "courses"
                ],
                "summary": "Create a new course",
                "parameters": [
                    {
                        "description": " ",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_ladmakhi81_learnup_internals_course_dto_req.CreateCourseReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/types.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_ladmakhi81_learnup_internals_course_dto_res.CreateCourseRes"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ApiResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/types.ApiResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/types.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ApiResponse"
                        }
                    }
                }
            }
        },
        "/courses/admin/page": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "courses"
                ],
                "summary": "Get list of paginated courses",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Page size",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/types.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/types.PaginationRes"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "data": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/github_com_ladmakhi81_learnup_internals_course_dto_res.GetCoursesRes"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/types.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ApiResponse"
                        }
                    }
                }
            }
        },
        "/users/admin/basic": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create Basic User",
                "parameters": [
                    {
                        "description": " ",
                        "name": "CreateBasicUserReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_ladmakhi81_learnup_internals_user_dto_req.CreateBasicUserReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/types.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_ladmakhi81_learnup_internals_user_dto_res.CreateBasicUserRes"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ApiError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_ladmakhi81_learnup_internals_auth_dto_req.LoginReq": {
            "type": "object",
            "required": [
                "password",
                "phone"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "github_com_ladmakhi81_learnup_internals_auth_dto_res.LoginRes": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                }
            }
        },
        "github_com_ladmakhi81_learnup_internals_category_dto_req.CreateCategoryReq": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "minLength": 3
                },
                "parentId": {
                    "type": "integer"
                }
            }
        },
        "github_com_ladmakhi81_learnup_internals_category_dto_res.CreateCategoryRes": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_ladmakhi81_learnup_internals_category_dto_res.GetCategoriesTreeItem": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "parentCategoryId": {
                    "type": "integer"
                },
                "subCategories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ladmakhi81_learnup_internals_category_dto_res.GetCategoriesTreeItem"
                    }
                }
            }
        },
        "github_com_ladmakhi81_learnup_internals_category_dto_res.GetCategoriesTreeRes": {
            "type": "object",
            "properties": {
                "categories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ladmakhi81_learnup_internals_category_dto_res.GetCategoriesTreeItem"
                    }
                }
            }
        },
        "github_com_ladmakhi81_learnup_internals_course_dto_req.CreateCourseReq": {
            "type": "object",
            "required": [
                "abilityToAddComment",
                "canHaveDiscount",
                "categoryId",
                "courseLevel",
                "description",
                "fee",
                "image",
                "introductionVideo",
                "name",
                "prerequisite",
                "price",
                "teacher_id",
                "thumbnailImage"
            ],
            "properties": {
                "abilityToAddComment": {
                    "type": "boolean"
                },
                "canHaveDiscount": {
                    "type": "boolean"
                },
                "categoryId": {
                    "type": "integer"
                },
                "commentAccessMode": {
                    "type": "string",
                    "enum": [
                        "all",
                        "students"
                    ]
                },
                "courseLevel": {
                    "type": "string",
                    "enum": [
                        "beginner",
                        "pre-intermediate",
                        "intermediate",
                        "advance"
                    ]
                },
                "description": {
                    "type": "string",
                    "minLength": 20
                },
                "discountFeeAmountPercentage": {
                    "type": "number",
                    "maximum": 100,
                    "minimum": 1
                },
                "fee": {
                    "type": "number",
                    "minimum": 0
                },
                "image": {
                    "type": "string",
                    "minLength": 10
                },
                "introductionVideo": {
                    "type": "string",
                    "minLength": 20
                },
                "maxDiscountAmount": {
                    "type": "number",
                    "minimum": 0
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 3
                },
                "prerequisite": {
                    "type": "string",
                    "minLength": 20
                },
                "price": {
                    "type": "number"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "teacher_id": {
                    "type": "integer"
                },
                "thumbnailImage": {
                    "type": "string",
                    "minLength": 10
                }
            }
        },
        "github_com_ladmakhi81_learnup_internals_course_dto_res.CreateCourseRes": {
            "type": "object",
            "properties": {
                "abilityToAddComment": {
                    "type": "boolean"
                },
                "canHaveDiscount": {
                    "type": "boolean"
                },
                "category_id": {
                    "type": "integer"
                },
                "commentAccessMode": {
                    "type": "string"
                },
                "courseStatus": {
                    "$ref": "#/definitions/github_com_ladmakhi81_learnup_internals_course_entity.CourseStatus"
                },
                "description": {
                    "type": "string"
                },
                "discountFeeAmountPercentage": {
                    "type": "number"
                },
                "fee": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "introductionVideo": {
                    "type": "string"
                },
                "isPublished": {
                    "type": "boolean"
                },
                "isVerifiedByAdmin": {
                    "type": "boolean"
                },
                "level": {
                    "type": "string"
                },
                "maxDiscountAmount": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "prerequisite": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "teacherId": {
                    "type": "integer"
                },
                "teacherIncomeAmount": {
                    "type": "number"
                },
                "thumbnailImage": {
                    "type": "string"
                },
                "verifiedByID": {
                    "type": "integer"
                },
                "verifiedDate": {
                    "type": "string"
                }
            }
        },
        "github_com_ladmakhi81_learnup_internals_course_dto_res.GetCoursesRes": {
            "type": "object",
            "properties": {
                "courses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ladmakhi81_learnup_internals_course_dto_res.courseItems"
                    }
                }
            }
        },
        "github_com_ladmakhi81_learnup_internals_course_dto_res.courseCategory": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "isPublished": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_ladmakhi81_learnup_internals_course_dto_res.courseItems": {
            "type": "object",
            "properties": {
                "category": {
                    "$ref": "#/definitions/github_com_ladmakhi81_learnup_internals_course_dto_res.courseCategory"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "introductionVideo": {
                    "type": "string"
                },
                "isPublished": {
                    "type": "boolean"
                },
                "isVerified": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "status": {
                    "$ref": "#/definitions/github_com_ladmakhi81_learnup_internals_course_entity.CourseStatus"
                },
                "statusChangedAt": {
                    "type": "string"
                },
                "teacher": {
                    "$ref": "#/definitions/github_com_ladmakhi81_learnup_internals_course_dto_res.courseTeacher"
                },
                "thumbnail": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "verifiedBy": {
                    "$ref": "#/definitions/github_com_ladmakhi81_learnup_internals_course_dto_res.courseUserVerifier"
                },
                "verifiedDate": {
                    "type": "string"
                }
            }
        },
        "github_com_ladmakhi81_learnup_internals_course_dto_res.courseTeacher": {
            "type": "object",
            "properties": {
                "fullName'": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "github_com_ladmakhi81_learnup_internals_course_dto_res.courseUserVerifier": {
            "type": "object",
            "properties": {
                "fullName'": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "github_com_ladmakhi81_learnup_internals_course_entity.CourseStatus": {
            "type": "string",
            "enum": [
                "starting",
                "in-progress",
                "done",
                "pause",
                "cancel"
            ],
            "x-enum-varnames": [
                "CourseStatus_Starting",
                "CourseStatus_InProgress",
                "CourseStatus_Done",
                "CourseStatus_Pause",
                "CourseStatus_Cancel"
            ]
        },
        "github_com_ladmakhi81_learnup_internals_user_dto_req.CreateBasicUserReq": {
            "type": "object",
            "required": [
                "firstName",
                "lastName",
                "password",
                "phone"
            ],
            "properties": {
                "firstName": {
                    "type": "string",
                    "minLength": 3
                },
                "lastName": {
                    "type": "string",
                    "minLength": 3
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "github_com_ladmakhi81_learnup_internals_user_dto_res.CreateBasicUserRes": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastName": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "types.ApiError": {
            "type": "object",
            "properties": {
                "message": {},
                "statusCode": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "integer"
                },
                "traceId": {
                    "type": "string"
                }
            }
        },
        "types.ApiResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "statusCode": {
                    "type": "integer"
                }
            }
        },
        "types.PaginationRes": {
            "type": "object",
            "properties": {
                "currentPage": {
                    "type": "integer"
                },
                "row": {},
                "totalCount": {
                    "type": "integer"
                },
                "totalPage": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Learnup",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
