basePath: /api
definitions:
  github_com_ladmakhi81_learnup_internals_auth_dto_req.LoginReq:
    properties:
      password:
        minLength: 8
        type: string
      phone:
        type: string
    required:
    - password
    - phone
    type: object
  github_com_ladmakhi81_learnup_internals_auth_dto_res.LoginRes:
    properties:
      accessToken:
        type: string
    type: object
  github_com_ladmakhi81_learnup_internals_user_dto_req.CreateBasicUserReq:
    properties:
      firstName:
        minLength: 3
        type: string
      lastName:
        minLength: 3
        type: string
      password:
        minLength: 8
        type: string
      phone:
        type: string
    required:
    - firstName
    - lastName
    - password
    - phone
    type: object
  github_com_ladmakhi81_learnup_internals_user_dto_res.CreateBasicUserRes:
    properties:
      createdAt:
        type: string
      firstName:
        type: string
      id:
        type: integer
      lastName:
        type: string
      phone:
        type: string
      updatedAt:
        type: string
    type: object
  types.ApiError:
    properties:
      message: {}
      statusCode:
        type: integer
      timestamp:
        type: integer
      traceId:
        type: string
    type: object
  types.ApiResponse:
    properties:
      data: {}
      statusCode:
        type: integer
    type: object
info:
  contact: {}
  title: Learnup
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/github_com_ladmakhi81_learnup_internals_auth_dto_req.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/types.ApiResponse'
            - properties:
                data:
                  $ref: '#/definitions/github_com_ladmakhi81_learnup_internals_auth_dto_res.LoginRes'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ApiError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.ApiError'
      summary: Login a user and return an access token
      tags:
      - auth
  /users/admin/basic:
    post:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: body
        name: CreateBasicUserReq
        required: true
        schema:
          $ref: '#/definitions/github_com_ladmakhi81_learnup_internals_user_dto_req.CreateBasicUserReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/types.ApiResponse'
            - properties:
                data:
                  $ref: '#/definitions/github_com_ladmakhi81_learnup_internals_user_dto_res.CreateBasicUserRes'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ApiError'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/types.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.ApiError'
      summary: Create Basic User
      tags:
      - users
swagger: "2.0"
